package com.lyh.itstudy.model;

import java.util.ArrayList;
import java.util.List;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category.cid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private Integer cid;

    private List<Categorysecond> CsList;

    public List<Categorysecond> getCsList() {
        return CsList;
    }

    public void setCsList(List<Categorysecond> csList) {
        CsList = csList;
    }

    /**
     *

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category.cname
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category.cid
     *
     * @return the value of tbl_category.cid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category.cid
     *
     * @param cid the value for tbl_category.cid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category.cname
     *
     * @return the value of tbl_category.cname
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category.cname
     *
     * @param cname the value for tbl_category.cname
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    @Override
    public String toString() {
        return "Category{" +
                "cid=" + cid +
                ", CsList=" + CsList +
                ", cname='" + cname + '\'' +
                '}';
    }
}