package com.lyh.itstudy.model;

import java.util.List;

public class Categorysecond {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_categorysecond.csid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private Integer csid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_categorysecond.csname
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private String csname;
    private List<Article> artList;

    public List<Article> getArtList() {
        return artList;
    }

    public void setArtList(List<Article> artList) {
        this.artList = artList;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_categorysecond.cid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private Integer cid;

    private String csimage;

    public String getCsimage() {
        return csimage;
    }

    public void setCsimage(String csimage) {
        this.csimage = csimage;
    }

    /**

     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_categorysecond.csid
     *
     * @return the value of tbl_categorysecond.csid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public Integer getCsid() {
        return csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_categorysecond.csid
     *
     * @param csid the value for tbl_categorysecond.csid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setCsid(Integer csid) {
        this.csid = csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_categorysecond.csname
     *
     * @return the value of tbl_categorysecond.csname
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public String getCsname() {
        return csname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_categorysecond.csname
     *
     * @param csname the value for tbl_categorysecond.csname
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setCsname(String csname) {
        this.csname = csname == null ? null : csname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_categorysecond.cid
     *
     * @return the value of tbl_categorysecond.cid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_categorysecond.cid
     *
     * @param cid the value for tbl_categorysecond.cid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    @Override
    public String toString() {
        return "Categorysecond{" +
                "csid=" + csid +
                ", csname='" + csname + '\'' +
                ", cid=" + cid +'\'' +
                ", csimage=" + csimage +
                '}';
    }
}