package com.lyh.itstudy.model;

import java.util.Date;

public class Replay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_replay.repid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private Integer repid;
    private Integer aid;

    public Integer getAid() {
        return aid;
    }

    public void setAid(Integer aid) {
        this.aid = aid;
    }

    private Article article;

    private User user;

    public Article getArticle() {
        return article;
    }

    public void setArticle(Article article) {
        this.article = article;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_replay.repdate
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private Date repdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_replay.uid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_replay.reptxt
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    private String reptxt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_replay.repid
     *
     * @return the value of tbl_replay.repid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public Integer getRepid() {
        return repid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_replay.repid
     *
     * @param repid the value for tbl_replay.repid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setRepid(Integer repid) {
        this.repid = repid;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_replay.repdate
     *
     * @return the value of tbl_replay.repdate
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public Date getRepdate() {
        return repdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_replay.repdate
     *
     * @param repdate the value for tbl_replay.repdate
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setRepdate(Date repdate) {
        this.repdate = repdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_replay.uid
     *
     * @return the value of tbl_replay.uid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_replay.uid
     *
     * @param uid the value for tbl_replay.uid
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_replay.reptxt
     *
     * @return the value of tbl_replay.reptxt
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public String getReptxt() {
        return reptxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_replay.reptxt
     *
     * @param reptxt the value for tbl_replay.reptxt
     *
     * @mbg.generated Sun Jan 26 12:38:17 GMT+08:00 2020
     */
    public void setReptxt(String reptxt) {
        this.reptxt = reptxt == null ? null : reptxt.trim();
    }

    @Override
    public String toString() {
        return "Replay{" +
                "repid=" + repid +
                ", aid=" + aid +
                ", repdate=" + repdate +
                ", uid=" + uid +
                ", reptxt='" + reptxt + '\'' +
                '}';
    }
}